Update sourcecode.rst
When installing the python wrapper, 

$ python setup.py build_ext -L ${LD_LIBRARY_PATH}

fails because -L requires an argument. I have tried interpreting it as in the proposed change, build_ext works then, but then the linking to the C++ library fails -- i.e. when I try to import PyCheMPS2, I get

ImportError: libchemps2.so.3: cannot open shared object file: No such file or directory

I assume my correction is not enough, maybe you can modify this better?